-- ============================================
-- CREATE/UPDATE ALL USERS WITH CORRECT PASSWORDS
-- ============================================
-- This script creates or updates all users with password123
-- Uses ON CONFLICT to update existing users
-- ============================================

-- BCrypt hash for password123 (generated by Spring Boot BCryptPasswordEncoder)
-- This is the same hash used throughout the application

-- Admin User (All pages access)
INSERT INTO users (username, password, email, full_name, role, active, created_at, updated_at)
VALUES (
    'admin',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- password123
    'admin@medicalstore.com',
    'System Administrator',
    'ADMIN',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO UPDATE
SET 
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    active = EXCLUDED.active,
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    updated_at = NOW();

-- Cashier (Billing access only)
INSERT INTO users (username, password, email, full_name, role, active, created_at, updated_at)
VALUES (
    'cashier',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- password123
    'cashier@medicalstore.com',
    'Cashier User',
    'CASHIER',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO UPDATE
SET 
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    active = EXCLUDED.active,
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    updated_at = NOW();

-- Stock Monitor (Inventory access only)
INSERT INTO users (username, password, email, full_name, role, active, created_at, updated_at)
VALUES (
    'stockmonitor',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- password123
    'stockmonitor@medicalstore.com',
    'Stock Monitor',
    'STOCK_MONITOR',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO UPDATE
SET 
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    active = EXCLUDED.active,
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    updated_at = NOW();

-- Stock Keeper (Medicines access only)
INSERT INTO users (username, password, email, full_name, role, active, created_at, updated_at)
VALUES (
    'stockkeeper',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- password123
    'stockkeeper@medicalstore.com',
    'Stock Keeper',
    'STOCK_KEEPER',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO UPDATE
SET 
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    active = EXCLUDED.active,
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    updated_at = NOW();

-- Customer Support (Returns access only)
INSERT INTO users (username, password, email, full_name, role, active, created_at, updated_at)
VALUES (
    'customersupport',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- password123
    'customersupport@medicalstore.com',
    'Customer Support Team',
    'CUSTOMER_SUPPORT',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO UPDATE
SET 
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    active = EXCLUDED.active,
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    updated_at = NOW();

-- Analyst (Reports access only)
INSERT INTO users (username, password, email, full_name, role, active, created_at, updated_at)
VALUES (
    'analyst',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- password123
    'analyst@medicalstore.com',
    'Data Analyst',
    'ANALYST',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO UPDATE
SET 
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    active = EXCLUDED.active,
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    updated_at = NOW();

-- Manager (Reports + Purchase History access)
INSERT INTO users (username, password, email, full_name, role, active, created_at, updated_at)
VALUES (
    'manager',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- password123
    'manager@medicalstore.com',
    'Manager',
    'MANAGER',
    true,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO UPDATE
SET 
    password = EXCLUDED.password,
    role = EXCLUDED.role,
    active = EXCLUDED.active,
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    updated_at = NOW();

-- ============================================
-- VERIFY ALL USERS
-- ============================================
SELECT 
    username,
    role,
    active,
    CASE 
        WHEN password = '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy' 
        THEN '✅ password123' 
        ELSE '❌ Different password' 
    END as password_status
FROM users
ORDER BY 
    CASE role
        WHEN 'ADMIN' THEN 1
        WHEN 'CASHIER' THEN 2
        WHEN 'STOCK_MONITOR' THEN 3
        WHEN 'STOCK_KEEPER' THEN 4
        WHEN 'CUSTOMER_SUPPORT' THEN 5
        WHEN 'ANALYST' THEN 6
        WHEN 'MANAGER' THEN 7
        ELSE 8
    END;

-- ============================================
-- EXPECTED: 7 users, all with password123
-- ============================================

